### ISSUE TITLE
Small request

### ISSUE THREAD

**Issue by mikhoul** [warren-bank/moz-rewrite#10]
Maybe adding a Enable/Disable button on the toolbar would be useful when we are testing.

Best Regards :smile:

**Comment by warren-bank** [comment]
Hi,

I've given this repo a little attention over the past few days.. a few updates. While I'm here, I'm also cleaning out some of the open issues.

Regarding the addon's UI and offering ways to quickly change commonly accessed preferences.. that's not really something I'm going to do. However, a while ago.. I did tweak another [addon](https://github.com/warren-bank/moz-prefbar/releases) that would server this purpose in a more general-purpose kind of way. The ["comments"](https://github.com/warren-bank/moz-prefbar#comments) sections of its README discusses this topic in more detail. I think you might like it :)

**Comment by warren-bank** [comment]
Actually, back in the day, it looks as though I used moz-rewrite (js) as a test subject for the work done in this other addon. This [sample data](https://github.com/warren-bank/moz-prefbar/blob/submenu_persistence/notes.txt#L592) appears to be properly formatted and ready for import.
