### ISSUE TITLE
redirectTo redirects the whole browser window?

### ISSUE THREAD

**Issue by mocking** [warren-bank/moz-rewrite#7]
I'm trying to replace the scripts loaded by a webpage by doing this, but now when a webpage loads that script, the whole browser gets redirected by redirectTo. I would expect only the script load gets redirected.

``` javascript
  {
    "url": /^https?:\/\/ajax.googleapis.com/i,
    "headers": function() {
      redirectTo(request.uri.href.replace("ajax.googleapis.com", "cdnjs.cloudflare.com"));
      return {};
    }
  }
```

**Comment by wyzegob** [comment]
waiting for 'redirectTo' everywhere ,not only reload the window.location.url.

**Comment by warren-bank** [comment]
Hi, sorry for not fixing this issue sooner.

An updated [version 1.05](https://github.com/warren-bank/moz-rewrite/releases/tag/js%2FCu.evalInSandbox%2Fv1.05) of the addon does exactly that. It's currently pending review on AMO, but works in versions of Firefox that still allow installation and use of unsigned addons (ex: Developer Edition, unbranded releases that are identical to those in the stable branch, etc)
