### ISSUE TITLE
Add console.log/debug/log (helper) function available to debug functions.

### ISSUE THREAD

**Issue by thomazz-nl** [warren-bank/moz-rewrite#8]
It would be convenient to write some variables/strings to the (browser) console  when debugging a function. I expected the "extensions.Moz-Rewrite.debug" preference to make some of the internal functions available but sadly it does not. Could you please consider?

Kind regards!

**Comment by warren-bank** [comment]
Hi,

Although I'd all but given up on doing any additional work on this addon, there was a fair bit of discussion in issue #11 after FF46 removed some javascript APIs that causes the addon to stop working.

While I had my hands in the code, I addressed your request and added a "log()" function that passes its parameters to "console.log()" of the active browser window. This feature was added in [v1.04](https://github.com/warren-bank/moz-rewrite/releases/tag/js%2FCu.evalInSandbox%2Fv1.04), and is available in all subsequent versions. [v1.05](https://github.com/warren-bank/moz-rewrite/releases/tag/js%2FCu.evalInSandbox%2Fv1.05) is currently the newest, and most likely will be the final release. (note: it's pending review on AMO)

As a side note, the boolean preference value "extensions.Moz-Rewrite.debug" is used internally to decide whether or not to open the flood gates and perform very verbose logging to the "Browser Console" (top navmenu: Tools > Web Developer > Browser Console). It prints checkpoints for nearly every operation it performs, which can be helpful for me to find the source of any problems if/when they occur. I'm not sure how useful it would be to the average user.

As you suggested, a simple "log()" statement that appears in the javascript console is probably much more useful for quickly testing a "rule" that's under development.
