### ISSUE TITLE
Not working in Firefox Developer Edition.

### ISSUE THREAD

**Issue by Ileca** [warren-bank/moz-rewrite#9]
I tried your add-on with the request rule sample, in fact, like you did in your video, and went to headers.jsontest.com to test it. No X-Custom-Sample-Header. I took my regular Firefox and it works.
I guess I am doomed to write _Not working in Firefox Developer Edition_ issues on github. Of course, I read the kilometers of doc... _before_.

Now that I am here, please enlighten the noob I am. Let says you cure this issue, could I use your add-on to redirect resources to other resources of my choice? And by redirection, I don't mean your redirectTo function. I need to do that redirection under Firefox Tracking Protection with the strict list. Basically, the strict list break every site importing jQuery with the google CDN. I want to redirect every request to that google resource to a safe one, the jQuery CDN itself. Problem: the Tracking Protection butt in and says that the resource was blocked. I guess your add-on can't do its job before the tracking protection detect the bad url?

**Comment by warren-bank** [comment]
Hi,

Regarding the addon not working in more recent versions of FF, there was a bit of recent discussion on that topic in issue #11 ..and there's an [updated version](https://github.com/warren-bank/moz-rewrite/releases/tag/js%2FCu.evalInSandbox%2Fv1.03) of the addon that's currently still pending review on AMO.

Regarding the ability to redirect individual page resources, that's the one bug that never got solved. In the earliest implementation of this addon, I was using the APIs as they were documented which should've allowed this behavior. However, testing showed that it never worked at all.. and the current implementation of "redirectTo" which occurs at the document-level was always just an incomplete workaround. If Firefox hadn't deprecated the entire (XPCOM/XUL) addon API.. and wasn't planning to remove it within the next few months, then I'd be willing to take another crack at finding a better workaround.. but that's not the reality. Sorry :/

**Comment by warren-bank** [comment]
Hi again,

Regarding the ability to redirect individual page resources, it's been addressed and fixed in an [updated version](https://github.com/warren-bank/moz-rewrite/releases/tag/js%2FCu.evalInSandbox%2Fv1.05) of the addon that's currently still pending review on AMO.
